# Add various configurations 

# Existing score sheets have some differences! 

# After add students data,  
# ensure there is a keyword "summary" 
# Ensure the sheet is well updated with current names 

# Must Have Key Words (once!):
# 'REG. NO.', 'INTERNAL EXAMINER MARKS /100'
# Input xlsx files must be named only as unit/subject code e.g. "EMT 4101.xlsx".

# Delete invisible files in a folder 
# e.g.: find . -type f -name '.~lock.*.xlsx#' -delete

[column_order]
columns = ["Ser. No.", "Reg. No.", "Name"] # DO NOT change this

[additional_columns]
columns = ["TU", "Total", "Mean", "Grade", "Status"]

[mechatronics_engineering_units]
path = "data/units/mechatronics_engineering_units.json"

[input_folder]
# path = "../individual_sheets"
# path = "../individual_sheets2"
path = "../2.1/sorted"

[running_report]
path = "../running_report.txt"

[consolidated_excel_output]
# path = "../EMT4_2_2023.xlsx"
# path = "../EMT2_2_2023.xlsx"
path = "../EMT_2.1_2023.xlsx"

[pass_list_pdf_output]
path = "../pass_list.pdf"

[supp_list_pdf_output]
path = "../supp_list.pdf"

[senate_documents_output]
path = "../senate_doc.pdf" 

[course_patterns]
E022 = "^E022-01-\\d+/\\d{4}$" # Mechatronics Engineering 
E023 = "^E023-\\d+-\\d+/\\d{4}$"

# E022 = "^E022[-‐]01[-‐]\\d+/\\d{4}$" # Ignore subtle hyphen variations
# ^(E0[‐-]022|EO[‐-]022)[-‐]01[-‐]\d+/\d{4}$ # o or O and 0 are different!

# Add more patterns for other courses if needed

# [semester_order]
# semester_4_1 = ["EMT 4101", "EMT 4102", "EMT 4103", "EMT 4104", "EMT 4105", "SMA 2272"]
# semester_4_2 = ["EMT 4201", "EMT 4202", "EMT 4203", "EMT 4204", "EMT 4205", "SMA 3261"]

[senate_documents_details]
university_name = "XYZ University"
school_of = "Engineering"
department_of = "Mechatronics Engineering"
course_name = "Bachelor of Science in Mechatronics Engineering"
academic_year = "2022/2023"
# year_of_study = "4"
# semester_of_study = "2"

[document_title]
document_title = """
{} <br />School of {} <br />Department of 
<u>{}</u> <br />{} <br />{} Academic Year <br />{} Year 
{} Semester Examination Results
"""

[pass_list_introduction]
pass_list_intro_content = """
The following <b>{} ({})</b> candidates have satisfied the School of 
{} Board of Examiners in the <b>{}</b> Academic Year, 
<b>{}</b> Year, <b>{}</b> Semester examination for the degree of 
{}. The School 
of {} Board of Examiners recommends that {}.
"""

[supp_list_introduction]
supp_list_intro_content = """
The following <b>{} ({})</b> candidates did not meet the 
requirements for the units specified next to their names during 
the <b>{}</b> Year <b>{}</b> Semester examinations for the {} 
degree in the <b>{}</b> Academic Year. The School of {} 
Board of Examiners recommends that <b>they take the supplementary units when they are 
next offered</b>.
"""

[document_signature_text]
document_signature_content = """
<b>Approved by the School Board of Examiners</b>
<br />
<br />
<b>Signed: ________________________________ Date: ____________________________</b>
<br />
<i>Dean, School of Engineering</i>
<br />
<br />
<b>Approved by the Senate</b>
<br />
<br />
<b>Signed: ________________________________ Date: ____________________________</b>
<br />
<i>Chairperson, Senate</i>
"""
